### ISSUE TITLE
When connecting to a PowerObjects hosted CRM 2015 IFD environment nothing appears when clicking Load Data

### ISSUE THREAD

**Issue by Josh-Dulabaum** [daggen/XrmToolBox-Plugins#1]

**Comment by daggen** [comment]
Hi Josh,
Sorry to hear about that. 
Does the "loading" message appear? Can you get it to work towards other organizations? Does other XRMtoolbox plugin work as expected? I really need to get more details if you expected me to help you.

**Comment by jduly** [comment]
Thank you for the quick response and sorry for not including more details.
-The"loading actors" message appears for 1-3 seconds
-I have tested the plugin with other organizations and it works great
-I have tested the plugin on other machines with the same results
-Other XRMtoolbox plugins work as expected when connected to the same organization

I am a big fan of this plugin and I am happy to provide additional information.

**Comment by daggen** [comment]
My first thoughts goes to if you have correct security role to see users, teams and security roles. Are you able to view does part in the web interface for CRM? Have you tried the other User and Securit Role plugins, think about the tool for assigning roles to users/teams and the one that checks which security roles that have a certain principle level. I just want to see if similar plugins can deal with your special situation.
