### ISSUE TITLE
No error when it doesn't work

### ISSUE THREAD

**Issue by MusicMonkey5555** [daggen/XrmToolBox-Plugins#3]
I was trying to assign a role to a disabled user and it looked like it worked and then I noticed after looking at it on the web it did nothing. I'm guessing this is because you can't assign a role to an unlicensed/disabled user. However I don't get a message or error or anything.

It would be nice to get some feedback when this happens.

**Comment by daggen** [comment]
Hi MusicMonkey,

Thanks for taking the time to give me feedback!
I'm missing some details in your scenario. Can you please confirm/add to the steps

1. You selected (using the select box) a disabled user
2. Select one or several roles to add to the user
3. Press "Add Roles"
4. Got a popup "Are you sure you would like to add selected security roles to enabled users/teams?" and pressed OK
5. Application showed the loading screen displaying with the users name
6. Application shows a popup with a counter for number of success, failed and ignored.

In step 6, did it show this as successful or ignored? The design is to show it as ignored for this case or cases when trying to add same role twice. Of course one could argue that there could be a better message. But before we start that discussion we need to see if there is a bug or this is just an enhancement.

**Comment by MusicMonkey5555** [comment]
It actually didn't show any of that. I just:
1. selected the user
2. selected the role
3. click assign rolls
4. Progress dialogue popped up and then disappeared with no feedback
displayed.

If you need versions or anything let me know.

**Comment by daggen** [comment]
Sounds like that you don't have the newest version 1.2017.7.10
