### ISSUE TITLE
Include team and include disabled does not apply to generated report

### ISSUE THREAD

**Issue by pipallnut** [daggen/XrmToolBox-Plugins#5]
XRM Toolbox version 1.2017.7.18
Plugin version 1.2016.10.2700
operating system - windows 10 enterprise build 10240

1. Open the report generator in XRM toolbox
2. Perform steps to select users etc...
3. make sure _"Include Teams"_ and _"Include disabled"_ checkboxes are unchecked
4. Click **Generate Report** and save to an accessible location
5. Open Report and you should see teams and disabled users included

**Expected result**
_Teams and disabled users not to be included in the report_

**Comment by daggen** [comment]
See your point. Will add it to the list

**Comment by daggen** [comment]
New version available. Go to plugin store and update. Please verify

**Comment by pipallnut** [comment]
Thanks daggen, will check and respond as soon as possible. Sorry for the late response.
