### ISSUE TITLE
Users,Team and security reports: missing users

### ISSUE THREAD

**Issue by NSR23** [daggen/XrmToolBox-Plugins#6]
This plug-in is just great. 
Unfortunately, I see active users in CRM that are not listed in the plug-in.

**Comment by daggen** [comment]
Thanks! Interesting. Can you share some more information
* How large set of users do you have?
* On prem or online?
* Is it something that sticks out with the missing users, i.e. the newest added users, with names late in the alphabet, belongs to a specific BU or have a certain security role

**Comment by NSR23** [comment]
Hi Jonathan
My answers, with some delay, I apologize


  *   We have about 700 users
  *   Online
  *   Seems that recent users are missing

KR
Nathalie

**Comment by daggen** [comment]
Strange, And I Assume it is the same if you generate the report. The users are missing? I know there is a problem if you have different names on same security role between different BUs. This happens when renaming the ootb roles in some cases.
