### ISSUE TITLE
Unable to Load Security Roles

### ISSUE THREAD

**Issue by crmnomad** [daggen/XrmToolBox-Plugins#7]
On version 1.2018.04.06 no issues, worked as before.  Updated to 1.2019.03.19 and now Security Roles do not load after Loading Actors.  Shows loading Actors and Loading Security Roles but Loading Actor Security Role Mapping does not appear.  

- Tried different laptop #2, with 2018.04.06 and same Organization and it works fine.  
- Tried same laptop #1 and a different Organization (on-prem) and it works fine.

Thanks

**Comment by daggen** [comment]
Is this still an issue with newer versions?

**Comment by crmnomad** [comment]
Hello, yes it is.  I updated and still same issue

 


Is this still an issue with newer versions?

**Comment by daggen** [comment]
Please add information regarding version of crm env, Xrmtoolbox version and plugin version. I cannot replicate it with my setup

**Comment by crmnomad** [comment]
9.1.0.6827  CRM ENV

 

1.2019.6.33  XRMTOOLBOX VER

 

1.2018.4.6  PLUGIN VER

 

Loads and everything works fine

 

~ ~ ~ ~

 

If I update the plugin ver and everything else is the same, is when I experience the issues of the Security Roles not populating when selecting LOAD DATA

 

 

Thank you!! 


 

 


Please add information regarding version of crm env, Xrmtoolbox version and plugin version. I cannot replicate it with my setup

**Comment by daggen** [comment]
I have had a similar issue before when the security roles didn't match between different BUs. But that should have been fixed by now. I've a dll which has logging enabled. Can you put in in your plugin folder. Test one more time and look in your logs dir and send med the logg. Thanks
[UserTeamSecurityRoleReporter.zip](https://github.com/daggen/XrmToolBox-Plugins/files/3592070/UserTeamSecurityRoleReporter.zip)

**Comment by crmnomad** [comment]
I did that but the only log file I saw updated is the XrmToolbox.PluginsStore.log, is that the file you need?

 

Sent: Monday, September 09, 2019 at 2:43 PM

**Comment by daggen** [comment]
Strange, then we don't have an exception while retrieving the data. Personally have I tried the tool with two different environments V9.1 online and have no trouble. So it must be environment specific. Cannot figure out what it could be.
I assume that you run as admin?

**Comment by crmnomad** [comment]
Yes, I am admin in CRM. 

 

It stays at loading Security Profiles for about 10 seconds and then populates the grid with no further messages to the screen that indicate progress as it does on my other computer using an earlier version.  Don't know if that observations helps.

 

Sent: Tuesday, September 10, 2019 at 2:59 PM

**Comment by daggen** [comment]
This is a great puzzle to me. How many security roles and Business unit do you have? Do you have Security roles defined not at BU top level?

Can you run this query in fetchxml builder.  See that there are values every where except Parent Role and nothing looks to strange.
<fetch>
  <entity name="role" >
    <attribute name="parentroleid" />
    <attribute name="name" />
    <attribute name="businessunitid" />
    <attribute name="parentrootroleid" />
  </entity>
</fetch>

**Comment by crmnomad** [comment]
I was able to connect to another organization with no issues so, it must be the company's organization where I am working.

 

There are about 95 sec roles and 230 BU.

 

Will run the query to get other information

 

Sent: Friday, September 13, 2019 at 3:52 PM

**Comment by daggen** [comment]
That is a quite big list. CRM actually stores each security role for each business unit. In your case you have almost 22k rows (230*95) of security roles. It might be a bit of challange for downloading all those rows to the tool hence the time. One of the changes between the versions is one extra column i started fetching which will have an impact on amount of data transferred. It should be slower but not drop dead.

**Comment by daggen** [comment]
Please try with this version instead. It should use the memory a bit better
[UserTeamSecurityRoleReporter.zip](https://github.com/daggen/XrmToolBox-Plugins/files/3613066/UserTeamSecurityRoleReporter.zip)

**Comment by crmnomad** [comment]
Hello!

That did it, I was able to complete loading the data for all the security roles.

Thank you very much!

 

Sent: Saturday, September 14, 2019 at 3:14 PM

**Comment by kmacmillan25** [comment]
Same problem here with CRM 2011 and the latest version of the plugin.... The log file says:

> PD CRM Prod	Error	System.AggregateException: One or more errors occurred. ---> System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: 'Team' entity doesn't contain attribute with Name = 'teamtype'.

**Comment by daggen** [comment]
I'm no longer active in the dynamics community. This repository is about to be archived.
