### ISSUE TITLE
Include privileges by role into report

### ISSUE THREAD

**Issue by dominicusmento** [daggen/XrmToolBox-Plugins#9]
Thanks for making this nice tool.
However what I miss is the privileges per role csv (table) and then in report 
privileges should be visible per user (merged from all the user roles).. 
Hopefully this is achievable..

**Comment by daggen** [comment]
Thanks
I did consider such a tool. But as there are other similar tools already available I skipped it. Sadly I'm about to archive this repository as I'm no longer active within dynamics
